"""Changed foreign key in case table

Revision ID: 7297f0557c80
Revises: d367bb2f549b
Create Date: 2022-01-27 14:39:43.292643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7297f0557c80'
down_revision = 'd367bb2f549b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prisoner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_court_cases_prisoner_doc_number_prisoners', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_court_cases_prisoner_id_prisoners'), 'prisoners', ['prisoner_id'], ['id'])
        batch_op.drop_column('prisoner_doc_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('court_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prisoner_doc_number', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_court_cases_prisoner_id_prisoners'), type_='foreignkey')
        batch_op.create_foreign_key('fk_court_cases_prisoner_doc_number_prisoners', 'prisoners', ['prisoner_doc_number'], ['doc_number'])
        batch_op.drop_column('prisoner_id')


    # ### end Alembic commands ###
